Feature add groceries
nocheacosador/SmartShopping pull request #21
Opened 2022-09-26 20:24 UTC by rytis17

Added new tab where you can add groceries with store name and prices.

2022-09-27 02:59 UTC, nocheacosador commented
It think this should have more functionality before it is merged. At least some validation that all of the input fields are filled in. Then store name I think should be a drop down list, etc.

2022-09-27 03:05 UTC, nocheacosador requested changes

2022-09-27 03:05 UTC, nocheacosador commented on ClientApp/src/components/Groceries.js
> +                <input type="text" ref="storeName"/>
Here you should use `<Input>` tag provided by `reactstrap`  package. It applies `bootstrap` theme that is global to the project. Same goes for `<button>` tag. You should use `<Button>` instead.

2022-09-27 03:05 UTC, nocheacosador commented on ClientApp/src/components/Groceries.js
> +            <table width="500">
I think `reactstrap` also has its own tag for tables, so you should use it to.

2022-09-27 13:51 UTC, dsemenas commented
You should also add field where it is possible to add date of purchase.

2022-10-03 15:21 UTC, nocheacosador approved these changes
Tight!

2022-10-03 15:21 UTC, merged